[package]
name = "bio-seq"
version = "0.12.1"
authors = ["jeff-k <jeff_k@fastmail.com>"]
edition = "2021"
description = "Bit packed and well-typed biological sequences"
homepage = "https://github.com/jeff-k/bio-seq"
documentation = "https://docs.rs/bio-seq"
license = "MIT"
keywords = ["bioinformatics", "genomics", "kmer", "dna", "iupac"]
readme = "../README.md"

#[dev-dependencies]
#bio-streams = { git="https://github.com/jeff-k/bio-streams.git" }
#clap = { version="4", features=["derive"] }

[dependencies]
bitvec = "1"
bio-seq-derive = { path = "../bio-seq-derive", version="2.0.1" }
serde = { version = "1", optional = true, features=["derive"] }
serde_derive = { version = "1", optional = true }

[features]
serde = ["dep:serde",  "dep:serde_derive"]

#[[example]]
#name = "aminokmers"
